apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
      - name: todo-client-app
        image: meharabdullah/todo-client-app:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todo-client-app-service
spec:
  type: LoadBalancer
  selector:
    app: todo-client-app
  ports:
  - port: 8081
    targetPort: 8081